# Cấu hình tất cả để log ra console
rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

# Sử dụng pattern layout để định dạng log
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Giảm bớt log không cần thiết từ một số thành phần cụ thể
logger.spark.name = org.apache.spark
logger.spark.level = warn


logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn
logger.metrics.name = org.apache.hadoop.metrics2.impl.MetricsConfig
logger.metrics.level = error

# Ẩn cảnh báo "Unable to load native-hadoop library"
logger.nativecode.name = org.apache.hadoop.util.NativeCodeLoader
logger.nativecode.level = error

# Ẩn c