# Set everything to be logged to the console
rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

# In the pattern layout, format the log messages
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Mute specific noisy components
logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn
