# Mặc định Spark chỉ biết SQL cơ bản. Dòng này "tiêm" thêm từ vựng SQL của Iceberg và Nessie 
# (Ví dụ: cho phép dùng lệnh CREATE BRANCH, MERGE BRANCH của Nessie)
spark.sql.extensions = org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions

# Đặt tên một cuốn sổ (catalog) là "nessie"
spark.sql.catalog.nessie = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.nessie.catalog-impl = org.apache.iceberg.nessie.NessieCatalog
# Địa chỉ để gọi API của Nessie (nằm ở container có tên "nessie", cổng 19120)
spark.sql.catalog.nessie.uri = http://nessie:19120/api/v1
# Mặc định đọc nhánh chính (main)
spark.sql.catalog.nessie.ref = main
# Định nghĩa thư mục gốc trong MinIO mà catalog này sẽ ghi dữ liệu vào
spark.sql.catalog.nessie.warehouse = s3a://warehouse/
spark.sql.catalog.nessie.authentication.type = NONE


# Spark sẽ dùng giao thức "s3a" (giả lập AWS S3) để nói chuyện với MinIO
spark.hadoop.fs.s3a.endpoint = http://minio:9000
spark.hadoop.fs.s3a.access.key = ${MINIO_ROOT_USER}
spark.hadoop.fs.s3a.secret.key = ${MINIO_ROOT_PASSWORD}
# Cực kỳ quan trọng: MinIO cần kiểu path-style để đọc đúng tên bucket
spark.hadoop.fs.s3a.path.style.access = true
spark.hadoop.fs.s3a.impl = org.apache.hadoop.fs.s3a.S3AFileSystem
# Tắt bảo mật SSL vì chạy ở local không có chứng chỉ HTTPS
spark.hadoop.fs.s3a.connection.ssl.enabled = false


# Đây là các thư viện bắt buộc. Khi Spark vừa bật lên, nó sẽ tự động lên mạng tải 4 cục này về:
# 1. Thư viện Iceberg cho Spark 3.5
# 2. Thư viện Nessie cho Spark
# 3 + 4. Thư viện Hadoop-AWS để Spark biết cách dùng giao thức s3a
# Bật Prometheus endpoint trên Spark UI (port 4040) để lấy executor metrics
# Endpoint: http://spark-master:4040/metrics/executors/prometheus
spark.ui.prometheus.enabled = true

spark.jars = /opt/bitnami/spark/custom-jars/iceberg-spark-runtime-3.5_2.12-1.6.0.jar,/opt/bitnami/spark/custom-jars/nessie-spark-extensions-3.5_2.12-0.99.0.jar,/opt/bitnami/spark/custom-jars/hadoop-aws-3.3.4.jar,/opt/bitnami/spark/custom-jars/aws-java-sdk-bundle-1.12.262.jar,/opt/bitnami/spark/custom-jars/wildfly-openssl-1.0.7.Final.jar

