{
 "title": "Lakehouse Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Spark Worker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\", instance=\"prometheus:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"postgresql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"minio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"airflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Airflow Task Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(airflow_ti_successes_total) or vector(0)) / ((sum(airflow_ti_successes_total) or vector(0)) + (sum(airflow_ti_failures_total) or vector(0))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Import Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{job=\"airflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Spark Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_master_workers_type_gauges{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Apps Working",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spark_master_apps_type_gauges{instance=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MinIO Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - minio_cluster_capacity_usable_free_bytes / minio_cluster_capacity_usable_total_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"airflow\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time Series Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Airflow Task Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(airflow_ti_successes_total[5m])",
     "legendFormat": "rate {{instance}} success"
    },
    {
     "expr": "rate(airflow_ti_failures_total[5m])",
     "legendFormat": "rate {{instance}} fail"
    }
   ]
  },
  {
   "title": "Spark JVM Heap (All nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", job=~\"spark.*\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests/Second to MinIO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Transactions/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"airflow\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}